[package]
name = "oneBlock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-bip39 = "1.0.0"
sp-core = "2.0.0"
sp-runtime = "2.0.0"
rocket_contrib = "0.4.10"